dim: 1536
in_dim: 36
ffn_dim: 8960
out_dim: 16
text_dim: 4096
freq_dim: 256
eps: 1e-6
patch_size: [1, 2, 2]
num_heads: 12
num_layers: 30
has_image_input: true
text_len: 512
in_dim_control_adapter: 24
num_control_block: 12